### ISSUE TITLE
sync API and CLI

### ISSUE THREAD

**Issue by rlcee** [fermitools/data_dispatcher#20]
The python API create_project requires a file list, and ignores the query.  The CLI project create accepts a query.  If the python will actually allow a functional query, please correct the comments and give the files argument a default.  If the query does not work, please make it work like the CLI - why should they be different?

**Comment by marcmengel** [comment]
The command-line client implements the query by calling the metacat server to get the file list.   So you need a metacat client and
a data_dispatcher client to do the same in Python.
