### ISSUE TITLE
project list features incomplete

### ISSUE THREAD

**Issue by rlcee** [fermitools/data_dispatcher#5]
`ddisp project list -s canceled`
doesn't seem to work (only -s that works is "active")

**Comment by marcmengel** [comment]
Hmm.. When I try it, `ddisp project list -s canceled` indeed does not work, but
`ddisp project list -s cancelled` (with 2 l's) does.   So I think the error here  is
more that we should check our -s argument for a valid status name...

**Comment by rlcee** [comment]
OK, I see cancelled works now, sorry for the mistake.  When I put in this ticket, I was also seeing that the other states produced no results.  Today, I also see no project other than cancelled.  I was expecting I left some done, failed, abandoned, but I don't see those.  Please check that the command is working for the other states.  I might be confused and actually all my projects are cancelled, in which case I'll produce some other states to check my claim.  Thanks

**Comment by marcmengel** [comment]
So looking in the database, there are projects with state='abandoned', which it does not list with `ddisp project list  -s abandoned`...  So there is something to chase there.

**Comment by marcmengel** [comment]
Ahh... so the api level has a "not_state" parameter to list_project, which defaults to "abandoned"; so it specifically won't list abandoned projects; the command line code or the API layer *could* override that if you *ask* specifically for abandoned projects...
